version: '3.8'

name: prueba-konecta
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./Back
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - database

  database:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: pruebaKonecta
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    tty: true

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./Front
    ports:
      - 3000:3000
    tty: true

volumes:
  database:
