version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./Back
    ports:
      - 8080:8080
    tty: true
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: pruebaKonecta
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pruebaKonecta"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./Front
    ports:
      - 3000:3000
    tty: true

volumes:
  database:
